twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%env(AWS_S3_VERSION)%' # OR 'latest' OR '2006-03-01'
        region: '%env(AWS_S3_REGION)%'
        credentials:
            key: '%env(AWS_S3_ACCESS_ID)%'
            secret: '%env(AWS_S3_ACCESS_SECRET)%'
        bucket_name: '%env(AWS_S3_BUCKET_NAME)%'